version: "3.9"

networks:
  learning:
    driver: "bridge"

services:
  svc-laravel-web-nginx:
    image: nginx:1.23-alpine
    command:
      # - nginx
      - nginx-debug
      - '-g'
      - 'daemon off;'
    environment:
      - NGINX_PORT=80
      # - NGINX_PORT=${LARAVEL_WEB_NGINX_HOST_HTTP_PORT}
      # - NGINX_HOST
      # - NGINX_ROOT_PATH=/var/www
      # /usr/share/nginx/html
      # - NGINX_LOGS_PATH=/var/log/nginx
      - PHP_UPSTREAM=svc-laravel-web-php-fpm:9000
    volumes:
      - ${LARAVEL_WEB_SRC}:/usr/share/nginx/html
      - ${LARAVEL_WEB_NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${LARAVEL_WEB_NGINX_DEFAULT_CONF}:/etc/nginx/templates/default.conf.template
      # - ${LARAVEL_WEB_NGINX_CONF}:/etc/nginx/nginx.conf
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - svc-laravel-web-php-fpm
    networks:
      - learning

  svc-laravel-web-php-fpm:
    image: php:7.4-fpm-alpine
    volumes:
      - ${LARAVEL_WEB_SRC}:/usr/share/nginx/html
    environment:
      - APP_URL=laravel.local
    env_file:
      - laravel-app-variables.env
    networks:
      - learning

